# Generated by Django 3.1.7 on 2021-03-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='')),
                ('min_to_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_now', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promoted', models.BooleanField()),
                ('auction_start_date', models.DateTimeField(auto_now=True)),
                ('auction_end_date', models.DateTimeField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auction.category')),
            ],
        ),
    ]
