# Generated by Django 3.1.7 on 2021-04-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20210402_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(default='Your city', max_length=60),
        ),
        migrations.AlterField(
            model_name='item',
            name='no_of_visits',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
